### ISSUE TITLE
[SR] Change in exit form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/sewa-rural#120]
ticket - https://avni.freshdesk.com/a/tickets/1220

Form - Exit form
Question - "Reason for exit" 
Add one new option - "Change of school outside intervention area"
Translation - ઇન્ટરવેંશન એરિયા સિવાયની શાળામાં ગયા 
(This reason should reflect in exit reason report)

**Comment by vindeolal** [comment]
- Changes are done and deployed on staging.

------For production follow the below steps------
- Create the new NA concept using avni-health-modules. Use the below script to add it to the answer. Can't use the JSON upload because there are a lot of concepts with the name 'Adolescent exit reason' and the server throws an error when a post is done using admin.
```
insert into concept_answer (concept_id, answer_concept_id, uuid, version, answer_order, audit_id, organisation_id)
values ((select id from concept where name = 'Adolescent exit reason' and organisation_id = 1),
        (select id from concept where name = 'Change of school outside intervention area'),
        'c04eb906-ec14-46fe-ac7e-8d21eb54d0b1',
        0,
        7,
        create_audit(),
        1)
```
